title: Ramblings of a Coder's Mind
author: Karun Japhet
email: karun@japhet.in

subtitle: Got Tech? Will Hack.
url: https://blog.karun.me
bio_url: https://karun.me

subscribe_rss: /atom.xml
simple_search: https://www.google.com/search
date_format: "ordinal"
time_format: "%H:%M %Z"
timezone: Asia/Kolkata

root: /
permalink: /blog/:year/:month/:day/:title/

plugins_dir: _plugins
sass_dir: _sass
code_dir: downloads/code
category_dir: blog/categories

markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes

highlighter: pygments.rb
paginate_path: "posts/:num"
excerpt_link: "Read on &rarr;"
excerpt_separator: "<!-- more -->"
recent_posts: 5
paginate: 10
titlecase: true

default_asides:
  - custom/asides/about.html
  - custom/asides/twitter.html
  - asides/recent_posts.html
  - custom/asides/social_links.html

disqus_short_name: roacm
disqus_show_comment_count: true

github_user: javatarz
github_repo_count: 3
github_skip_forks: true
github_show_profile_link: true

facebook_user: KarunJaphet
twitter_user: javatarz
twitter_widget_id: 660845451051008000
twitter_tweet_button: true

markdown: kramdown
theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-target-blank
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

social_links:
  -
    user: javatarz
    base_url: https://github.com/
    title: GitHub
    icon_name: fa-github
  -
    user: 499797
    base_url: https://stackoverflow.com/users/
    title: Stack Overflow
    icon_name: fa-stack-overflow
  -
    user: javatarz
    base_url: https://twitter.com/
    title: Twitter
    icon_name: fa-twitter
  -
    user: karunjaphet
    base_url: https://www.linkedin.com/in/
    title: LinkedIn
    icon_name: fa-linkedin
